version: "3.8"

services:
  db:
    image: postgres:15
    container_name: todo_db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - todo_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: todo_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://todo_user:password@db:5432/todo_db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  todo_data:
